---
AWSTemplateFormatVersion: '2010-09-09'
Description: "Deploy AWS infrastructure: ECR repo"

Parameters:
  ProjectName:
    Type: String
  BranchName:
    Type: String
    Description: "The deployment environment" 
    AllowedValues:
      - "dev"
      - "uat"
      - "prod"

Resources:
  ECRRepository:
    Type: AWS::ECR::Repository
    Properties:
      # LifecyclePolicy: TBD
      Tags:
        - Key: CreatedBy
          Value: joelbarenco
        - Key: Environment
          Value: !Ref BranchName
        - Key: Name
          Value: !Sub ${ProjectName}-ECRRepository-${BranchName}
        - Key: Product
          Value: tbd
        - Key: Project
          Value: !Sub ${ProjectName}
        - Key: Repo
          Value: https://github.com/wantedmedia/movieapi

Outputs:
  ECRRepository:
    Description: "Name of the ECR repo"
    Value: !Ref ECRRepository
    Export:
      Name: !Sub ${ProjectName}-ECRRepository-${BranchName}

# output sample: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/continuous-delivery-codepipeline-parameter-override-functions.html