---
AWSTemplateFormatVersion: '2010-09-09'
Description: "Docker Repo"

Parameters:
  ProjectName:
    Type: String
  BranchName:
    Type: String
    Description: "The deployment environment" 
    AllowedValues:
      - "dev"
      - "uat"
      - "prod"
  ECRRepositoryName:
    Type: String
    Description: "ECR repository where to push the docker image"

Resources:
  CodeBuild:
    Type: AWS::CodeBuild::Project
    Properties:
      Artifacts:
        Type: CODEPIPELINE
      Description: 'Build and deploy container to ECR'
      Environment:
        ComputeType: BUILD_GENERAL1_SMALL
        Type: LINUX_CONTAINER
        Image: aws/codebuild/amazonlinux2-x86_64-standard:2.0
        PrivilegedMode: true
        EnvironmentVariables:
          - Name: IMAGE_REPO_NAME
            Type: PLAINTEXT
            Value: !Ref ECRRepositoryName
          - Name: IMAGE_TAG
            Type: PLAINTEXT
            Value: "latest"
          - Name: AWS_ACCOUNT_ID
            Type: PLAINTEXT
            Value: !Ref AWS::AccountId
          - Name: AWS_DEFAULT_REGION
            Type: PLAINTEXT
            Value: !Ref AWS::Region
      Name: !Sub "${ProjectName}-build-${BranchName}"
      ServiceRole: !GetAtt CodeBuildRole.Arn
      Source:
        Type: CODEPIPELINE
      Tags:
        - Key: CreatedBy
          Value: joelbarenco
        - Key: Environment
          Value: !Ref BranchName
        - Key: Name
          Value: !Sub ${ProjectName}-codeBuildProject-${BranchName}
        - Key: Product
          Value: tbd
        - Key: Project
          Value: !Sub ${ProjectName}
        - Key: Repo
          Value: https://github.com/wantedmedia/movieapi

  CodeBuildRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - codebuild.amazonaws.com
            Action:
              - sts:AssumeRole
      Path: /
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AWSCodeBuildAdminAccess
        - arn:aws:iam::aws:policy/CloudWatchLogsFullAccess
        - arn:aws:iam::aws:policy/AmazonS3FullAccess
      Policies:
        - PolicyName: code-build
          PolicyDocument:
            Statement:
              - Effect: Allow
                Action:
                  - ecr:*
                Resource: "*"
      Tags:
        - Key: CreatedBy
          Value: joelbarenco
        - Key: Environment
          Value: !Ref BranchName
        - Key: Name
          Value: !Sub ${ProjectName}-codeBuildIAMRole-${BranchName}
        - Key: Product
          Value: tbd
        - Key: Project
          Value: !Sub ${ProjectName}
        - Key: Repo
          Value: https://github.com/wantedmedia/movieapi
