---
AWSTemplateFormatVersion: '2010-09-09'
Description: 'Movie API ECS infrastructure'

Parameters:
  Name:
    Type: String
    Default: api-movie
    Description: Name of the API to identify associated resources. 
  Environment:
    Type: String
    Description: The deployment environment 
    AllowedValues:
      - dev
      - uat
      - prod
  AwsAccountId:
    Type: String
    Description: AWS Elastic Load Balancing Account ID used to allow ELBs access to the S3 bucket storing the logs. Default value is for eu-west-1
    Default: "073919355633"

Resources:
  EC2Instance:
    Type: AWS::EC2::Instance
    Properties: 
      ImageId: ami-06ce3edf0cff21f07
      InstanceType: t2.micro
      Tags:
        - Key: CreatedBy
          Value: joelbarenco
        - Key: Environment
          Value: !Ref Environment
        - Key: Name
          Value: !Sub ${Name}-ecr_repo-${Environment}
        - Key: Product
          Value: tbd
        - Key: Repo
          Value: tbd

  ############################
  TaskRole:
    Type: AWS::IAM::Role

  ############################
  S3LogsBucket:
    Type: AWS::S3::Bucket

  ContentBucketPolicy:
    Type: AWS::S3::BucketPolicy

  ############################
  SSMServiceName:
    Type: AWS::SSM::Parameter
