---
AWSTemplateFormatVersion: '2010-09-09'
Description: Creates the ECR repo that will host the code for the movie API service

Parameters:
  AccountId:
    Type: String
    Default: 073919355633
  Name:
    Type: String
    Default: api-movie
    Description: Name of the API to identify associated resources. 
  DevEnvironment:
    Type: String
    Description: The deployment environment 
    AllowedValues:
      - dev
      - uat
      - prod
    Default: prod

Resources:
  ECR:
    Type: AWS::ECR::Repository
    Properties:
      ## set up lifecyle policy
      # LifecyclePolicy: TBD
      Tags:
        - Key: CreatedBy
          Value: joelbarenco
        - Key: Environment
          Value: !Ref DevEnvironment
        - Key: Name
          Value: !Sub ${Name}-ecr_repo-${DevEnvironment}
        - Key: Product
          Value: tbd
        - Key: Repo
          Value: https://github.com/wantedmedia/movieapi

